apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: helloworld
  namespace: default
spec:
  interval: 1m0s
  component: github.com/helloworld
  version:
    semver: ">=v1.0.0"
  repository:
    url: ghcr.io/mlade77