### Това казва на Flux-a какво да инсталира
### Вкарва го в source.toolkit.fluxcd.io/HelmRepository CRD
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocm-controller
  namespace: ocm-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ocm-controller
      version: v0.26.6
      sourceRef:
        kind: HelmRepository
        name: ocm-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    manager:
      replicaCount: 1
    registry:
      tls:
        enabled: false
