{{/* 
  2025-06-10 : 
  Switched from generating this with controller-gen to maintaining it by hand.  
  See https://github.com/open-component-model/ocm-project/issues/518
*/ -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocm-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocm-controller-manager-role
subjects:
- kind: ServiceAccount
  name: ocm-controller
  namespace: {{ .Release.Namespace }}
